In [82]:
!pip install numpy
!pip install pandas
import numpy as np
import pandas as pd



[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: C:\Users\lekha\AppData\Local\Programs\Python\Python313\python.exe -m pip install --upgrade pip



[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: C:\Users\lekha\AppData\Local\Programs\Python\Python313\python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,'a'])

In [4]:
a

array(['1', '2', '3', '4', 'a'], dtype='<U21')

In [5]:
a = np.array(10)
b = np.array([1,2,3])
c = np.array([[1,2,3],[4,5,6]])

In [6]:
print('a dimension:', a.ndim)
print('b dimension:', b.ndim)
print('c dimension:',c.ndim)
print('shape of a:', a.shape)
print('shape of b:', b.shape)
print('shape of c:',c.shape)
print(c.dtype)
print(type(b))
print(len(c))

a dimension: 0
b dimension: 1
c dimension: 2
shape of a: ()
shape of b: (3,)
shape of c: (2, 3)
int64
<class 'numpy.ndarray'>
2


In [7]:
np.eye(3)
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [8]:
np.ones((3,2),dtype='int')

array([[1, 1],
       [1, 1],
       [1, 1]])

In [9]:
np.full((3,2),5,dtype='int') 



array([[5, 5],
       [5, 5],
       [5, 5]])

In [10]:
x = [1,2,3,4,5]
np.diag(x)


array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [11]:
x = np.arange(1,17)
n1=x.reshape((4,4))
print(n1)
n2=x.reshape(2,8)
print(n2)
n3=x.reshape(2,4,2)
print(n3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]]


In [12]:
arr = np.arange(1,10).reshape(3,3)
ravel_arr = arr.ravel()
ravel_arr[0]=1001
print(arr)
print("\nravel 1D array:")
print(ravel_arr)

[[1001    2    3]
 [   4    5    6]
 [   7    8    9]]

ravel 1D array:
[1001    2    3    4    5    6    7    8    9]


In [13]:
arr = np.arange(1,10).reshape(3,3)
flatten_arr = arr.flatten()
flatten_arr[0]=1001
print("Original 2D arr:")
print(arr) 

print("\nFlattened 1D array:")
print(flatten_arr)  

Original 2D arr:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Flattened 1D array:
[1001    2    3    4    5    6    7    8    9]


In [14]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a[0,1])


2


In [15]:
a=np.array([
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],        # Layer 0
    [[10, 11, 12], [13, 14, 15], [16, 17, 18]] # Layer 1
])

print(a[0][2][2])

9


In [26]:
a=np.arange(1,11)
print(a)
a[1:6]
arr=np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
arr[0:2,1:3]


[ 1  2  3  4  5  6  7  8  9 10]


array([[2, 3],
       [5, 6]])

In [54]:
x1=np.arange(6)
x1
x2=x1
x2[0]=10
print(x1)
print(x2)
print(id(x1))
print(id(x2))
x3=x1.view()
np.shares_memory(x1,x3)
x3[0]=100
print(x1)
print(x3)
x4=x1.copy()
np.shares_memory(x1,x4)
x4[-1]=900
print(x1)
print(x4)
x1==x4

[10  1  2  3  4  5]
[10  1  2  3  4  5]
2048484194992
2048484194992
[100   1   2   3   4   5]
[100   1   2   3   4   5]
[100   1   2   3   4   5]
[100   1   2   3   4 900]


array([ True,  True,  True,  True,  True, False])

In [49]:

a=np.array([[1,2,3],
   [4,5,6],
   [7,8,9]])
a[a>3]
a[(a>3)&(a<6)]

array([4, 5])

In [53]:
x1 = np.array([1,2,3])
x4 = np.array([1,2,200])

print(x1 == x4) 

[ True  True False]


In [57]:
a = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
print(a.transpose())

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [59]:
a = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
b = np.array([[10,11,12],
              [13,14,15],
              [16,17,18]])
np.vstack((a,b))
np.hstack((a,b))


array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

In [62]:
a = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
a = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
np.insert(a,4,10)

array([1, 2, 3, 4, 6, 7, 8, 9])

In [63]:
a = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
np.delete(x1,2)

array([100,   1,   3,   4,   5])

In [66]:
a = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
np.sin(a)
np.sum(a,axis=0)
np.sum(a,axis=1)

array([ 6, 15, 24])

In [80]:
print(dir(list))
import keyword
print(keyword.kwlist)
print(len(keyword.kwlist))

['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']
['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']
35
